### ISSUE TITLE
This is @leycec. I am abusing this unrelated issue tracker to say...

### ISSUE THREAD

**Issue by leycec** [langfield/hask#1]
**THANK YOU SO MUCH!!!** Also, I am so sorry for not promptly attending to your GitHub Sponsors subscription. :sob:

I completely dropped the ball and then sat on that ball. I feel just awful. I have no excuse for my poor behaviour except for Asperger's – the social handicap that imbues me with intellectual superpowers but the social skills of an obnoxious gnat that you can't help but feed to the hungry spider quietly living above your bed. Frankly, the cost is too high. I frequently neglect real-world necessities like bathing, socializing, and checking e-mail. Life became a bit of a mad-house for our family this past summer and... well, I accidentally stopped checking e-mail again. It happened. Again.

I wasn't even aware of your phenomenal generosity. It pains me. I'm so tremendously grateful for what you did. Living in a cottage in the Canadian wilderness comes with its share of joyful memories, but also pain points. Biosecurity tickets (i.e., this thing people tell me is called "money") is one of them. You eased our family's financial burden. I will *always* remember you for that.

I'm so sorry, bro. I hope you can forgive me. As a means of amends, I'd like to advertise you or an affiliated website of you at [beartype's official docos site](https://beartype.readthedocs.io). Please e-mail me at your leisure and I will gratefully do your bidding for all time:

    leycec@gmail.com  # <-- this is me

**P.S.:** I failed to grep your e-mail from your GitHub commit messages. I even Google-stalked you... but you have hidden yourself well. You're like the Bourne Identity of open-source advocates. This left me with little choice but to publicize my shame on this unrelated issue tracker, which I also now feel bad about.

> Asperger's: *this is why we can't have good things.* `</sigh>`

**Comment by langfield** [comment]
@leycec Good to hear from you! 🙂 No worries! I saw your roadmap in my inbox, looking forward to those deeply-checked containers!

**Comment by leycec** [comment]
**You're too nice!** Seriously. You're too nice. I still feel super-bad about neglecting you, despite you being so nice. Just drop me a line whenever at either the above e-mail or @beartype's issue tracker with your preferred URL and I will *immediately* promote that URL forever at [@beartype's official docos site](https://beartype.readthedocs.io). This I swear.

And... thanks for being so understanding. I'm trying to do better with respect to human communication. I'll get there someday! Lastly, I'm delighted that you're digging deep into Haskell. It looks like you're having so much fun here and in your other Haskell projects. Pure functional languages really are the bee's knees, aren't they? Yes, they really are. :bee:  :kneeling_man:
